<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Name | Portfolio</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            line-height: 1.6;
        }
        header {
            background: #333;
            color: #fff;
            padding: 1rem 2rem;
            text-align: center;
        }
        nav a {
            color: #fff;
            margin: 0 15px;
            text-decoration: none;
        }
        section {
            padding: 2rem;
        }
        .portfolio-item {
            margin-bottom: 1.5rem;
        }
        footer {
            text-align: center;
            padding: 1rem;
            background: #f4f4f4;
            margin-top: 2rem;
        }
    </style>
</head>
<body>

    <header>
        <h1>Your Name</h1>
        <p>Web Developer | Designer | Programmer</p>
        <nav>
            <a href="#about">About</a>
            <a href="#portfolio">Portfolio</a>
            <a href="#contact">Contact</a>
        </nav>
    </header>

    <section id="about">
        <h2>About Me</h2>
        <p>Hello! I'm a passionate developer who loves building simple and beautiful websites. I specialize in front-end development and have experience with HTML, CSS, JavaScript, and various frameworks.</p>
    </section>

    <section id="portfolio">
        <h2>My Work</h2>
        <div class="portfolio-item">
            <h3>Project One</h3>
            <p>A brief description of your project. Include what technologies you used and your role.</p>
        </div>
        <div class="portfolio-item">
            <h3>Project Two</h3>
            <p>A brief description of another project. Try to include links if it's live or on GitHub.</p>
        </div>
    </section>

    <section id="contact">
        <h2>Contact Me</h2>
        <p>Feel free to reach out if you'd like to work together or have any questions.</p>
        <p>Email: <a href="mailto:your.email@example.com">your.email@example.com</a></p>
        <p>LinkedIn: <a href="https://linkedin.com/in/yourprofile" target="_blank">yourprofile</a></p>
    </section>

    <footer>
        <p>&copy; 2025 Your Name. All rights reserved.</p>
    </footer>

</body>
</html>
